# Run `travis lint` when changing this file to avoid breaking the build.


# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - ip a
  - ip r ls
  - hostname -I
  - sudo cat /etc/default/docker
  - chmod 600 brooklyn.properties
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - echo "Host localhost" >> /home/travis/.ssh/config
  - echo "    StrictHostKeyChecking no" >> /home/travis/.ssh/config
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - chmod g-rw,o-rw /home/travis/.ssh/*
  # Manually install and run brooklyn as it isn't an available service
  - curl -SL https://repository.apache.org/content/repositories/releases/org/apache/brooklyn/brooklyn-dist/0.10.0/brooklyn-dist-0.10.0-dist.tar.gz | tar xz
  - nohup bash -c "cd brooklyn-dist-* && bin/brooklyn launch >/dev/null 2>&1 &"
  
install:
  # Override default travis to use the maven wrapper
  # skip license on travis due to #1512
  #- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dlicense.skip=true
  - mvn verify

script:
#  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

